### PR TITLE
Add optional utilities for conversion to a DataFrame and for plotting with Gadfly

### PR DESCRIPTION
**Pull request by tshort**
This adds a dependency on Requires.jl. It's a small package that has worked well for me. The main advantage of this code is that it gives us a quick way to plot AxisArrays using Gadfly.

Note that this also requires the development version of DataFrames (I added a feature needed for this).

Note that this causes a ton of warnings when DataFrames and Gadfly are loaded. Most are due to other packages, but some are ambiguity warnings between DataArrays and AxisArrays. DataArrays will probably undergo a lot of change as they convert to some sort of Nullables representation, so I wouldn't worry about these for now. Ambiguity warnings are a PITA. Hopefully, Jeff's type work will fix all that.

### CODE REVIEW

**Comment by mbauman** [comment]
Yes, now the real fun can begin! Good call on `@require` -- that seems to be the way to go here. I don't have computer access for the next few days, so you can take charge on the merge button. 

I think we can have separate test REQUIRES file, so that'd be something to look into eventually (but isn't really critical for now).

**Comment by timholy** [comment]
`Requires` is a brilliant package, but it does some [seriously-scary surgery](https://github.com/MikeInnes/Requires.jl/blob/5683745f03cbea41f6f053182461173e236fdd94/src/require.jl#L9-L15), the tagged version is broken, and on julia-0.5 generates the following unavoidable warning:
```jl
julia> using AxisArrays
WARNING: Method definition require(Symbol) in module Base at loading.jl:317 overwritten in module AxisArrays at /home/tim/.julia/v0.5/Requires/src/require.jl:12.
```

I'd like to recommend that we follow [@tkelman's advice](https://github.com/JuliaLang/julia/issues/14883#issuecomment-235166045). Can this functionality be moved to a separate package?

**Comment by mbauman** [comment]
Yup, I fully support that.

**Comment by timholy** [comment]
@tshort, are you OK with that? If so, do you want to host the package? Or put it at JuliaStats? I don't have commit access there, so I couldn't host it. If needed I'll start a package and request that it be transferred to a suitable home.

**Comment by tshort** [comment]
I'd prefer just deleting/disabling the code and waiting until we get the extern keyword (https://github.com/JuliaLang/julia/issues/15705).

**Comment by timholy** [comment]
I agree, the world is waiting eagerly for `extern`.

OK, I can do that. Thanks to git it's easy to get back. Thanks for your flexibility!

**Comment by timholy** [comment]
For the record, commit 08f266dce5a68844e7ee7d7ab630ffc820ba7f07 has `utils.jl`.

**Pull request merged**
